import { afterEach, describe, expect, it } from 'vitest';
import { mkdtempSync, readdirSync, readFileSync, rmSync, utimesSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { CookieJarStore } from '@main/cookies/cookie-jar-store.js';
import { computeCookieFingerprint, cookiesChangedSinceBlock } from '@main/cookies/cookie-fingerprint.js';
import { CookieService } from '@main/cookies/cookie-service.js';
import { defaultAppSettings } from '@main/settings/defaults.js';
import type { AppSettings } from '@shared/types/domain.js';

// Tệp do APP ghi chỉ có dòng tiêu đề Netscape; tệp do yt-dlp ghi lại có thêm dòng "generated by yt-dlp".
const APP_SAVED_A = '# Netscape HTTP Cookie File\r\n.youtube.com\tTRUE\t/\tTRUE\t2147483647\tSID\tgia-tri-a\r\n';
const APP_SAVED_B = '# Netscape HTTP Cookie File\r\n.youtube.com\tTRUE\t/\tTRUE\t2147483647\tSID\tgia-tri-b\r\n';
const YTDLP_ROTATED = (tag: string): string =>
  '# Netscape HTTP Cookie File\n# This file is generated by yt-dlp.  Do not edit.\n\n' +
  `.youtube.com\tTRUE\t/\tTRUE\t2147483647\tSID\tgia-tri-a\n.youtube.com\tTRUE\t/\tTRUE\t2147483647\t__Secure-3PSIDTS\txoay-${tag}\n`;

let folder = '';
afterEach(() => {
  if (folder) rmSync(folder, { recursive: true, force: true });
  folder = '';
});

interface Setup {
  security: string;
  file: string;
  jar: CookieJarStore;
  settings: AppSettings;
  service: CookieService;
}

function setup(): Setup {
  folder = mkdtempSync(join(tmpdir(), 'tubmedia-cookie-jar-'));
  const security = join(folder, 'security');
  const file = join(security, 'cookies-managed.txt');
  const settings: AppSettings = { ...defaultAppSettings, cookiesFilePath: '', cookiesBrowser: 'none', cookiesBrowserProfile: '' };
  const settingsService = {
    get: () => settings,
    update: (patch: Partial<AppSettings>) => Object.assign(settings, patch)
  };
  const jar = new CookieJarStore(security);
  const service = new CookieService(folder, settingsService as never, jar);
  return { security, file, jar, settings, service };
}

/** Dấu vân tay "lúc bị chặn" đúng như QueueManager lưu. */
async function blockedNow(s: Setup): Promise<unknown> {
  return JSON.parse(JSON.stringify(await computeCookieFingerprint(s.settings, s.jar))) as unknown;
}

async function changed(s: Setup, stored: unknown, trigger: 'startup' | 'cookies-saved' = 'startup'): Promise<boolean> {
  return cookiesChangedSinceBlock(stored, await computeCookieFingerprint(s.settings, s.jar), null, trigger);
}

describe('cookies: yt-dlp nhận bản sao tạm riêng, ghi ngược có kiểm soát', () => {
  it('yt-dlp không bao giờ được trao đường dẫn tệp gốc; mỗi lượt có bản sao riêng', async () => {
    const s = setup();
    await s.service.saveText(APP_SAVED_A);
    const first = await s.jar.lease(s.settings);
    const second = await s.jar.lease(s.settings);
    expect(first.settings?.cookiesFilePath).not.toBe(s.file);
    expect(second.settings?.cookiesFilePath).not.toBe(first.settings?.cookiesFilePath);
    expect(readFileSync(first.settings!.cookiesFilePath, 'utf8')).toBe(APP_SAVED_A);
    await first.release('aborted');
    await second.release('aborted');
    expect(readdirSync(join(s.security, 'cookie-runs'))).toHaveLength(0);
  });

  it('yt-dlp tự làm mới cookies: được ghi ngược vào tệp gốc nhưng KHÔNG tính là cookies mới', async () => {
    const s = setup();
    await s.service.saveText(APP_SAVED_A);
    const stored = await blockedNow(s);

    const lease = await s.jar.lease(s.settings);
    writeFileSync(lease.settings!.cookiesFilePath, YTDLP_ROTATED('1'));
    await lease.release('success');

    expect(readFileSync(s.file, 'utf8')).toBe(YTDLP_ROTATED('1'));
    expect(await changed(s, stored)).toBe(false);
  });

  it('lượt lỗi cookies (hoặc bị hủy) không ghi ngược', async () => {
    const s = setup();
    await s.service.saveText(APP_SAVED_A);
    const failed = await s.jar.lease(s.settings);
    writeFileSync(failed.settings!.cookiesFilePath, YTDLP_ROTATED('loi'));
    await failed.release('cookie-failure');
    const aborted = await s.jar.lease(s.settings);
    writeFileSync(aborted.settings!.cookiesFilePath, YTDLP_ROTATED('huy'));
    await aborted.release('aborted');

    expect(readFileSync(s.file, 'utf8')).toBe(APP_SAVED_A);
  });

  it('lưu cookies MỚI qua app: tính là đổi; lưu lại đúng nội dung cũ qua app: không tính', async () => {
    const s = setup();
    await s.service.saveText(APP_SAVED_A);
    const stored = await blockedNow(s);

    await s.service.saveText(APP_SAVED_A);
    expect(await changed(s, stored, 'cookies-saved')).toBe(false);

    await s.service.saveText(APP_SAVED_B);
    expect(await changed(s, stored, 'cookies-saved')).toBe(true);
  });

  it('người dùng sửa tệp bên ngoài app: tính là đổi', async () => {
    const s = setup();
    await s.service.saveText(APP_SAVED_A);
    const lease = await s.jar.lease(s.settings);
    writeFileSync(lease.settings!.cookiesFilePath, YTDLP_ROTATED('1'));
    await lease.release('success');
    const stored = await blockedNow(s);

    writeFileSync(s.file, APP_SAVED_B);
    expect(await changed(s, stored)).toBe(true);
  });

  it('hai tiến trình chạy song song không làm hỏng tệp gốc', async () => {
    const s = setup();
    await s.service.saveText(APP_SAVED_A);
    const leases = await Promise.all(Array.from({ length: 6 }, () => s.jar.lease(s.settings)));
    leases.forEach((lease, index) => writeFileSync(lease.settings!.cookiesFilePath, YTDLP_ROTATED(String(index))));

    await Promise.all(leases.map((lease) => lease.release('success')));

    const final = readFileSync(s.file, 'utf8');
    expect(leases.map((_, index) => YTDLP_ROTATED(String(index)))).toContain(final);
    expect(readdirSync(s.security).filter((name) => name.includes('.tmp'))).toHaveLength(0);
    expect(readdirSync(join(s.security, 'cookie-runs'))).toHaveLength(0);
  });

  it('người dùng lưu cookies mới trong lúc yt-dlp đang chạy: không bị bản sao cũ ghi đè', async () => {
    const s = setup();
    await s.service.saveText(APP_SAVED_A);
    const lease = await s.jar.lease(s.settings);
    await s.service.saveText(APP_SAVED_B);
    writeFileSync(lease.settings!.cookiesFilePath, YTDLP_ROTATED('cu'));

    await lease.release('success');

    expect(readFileSync(s.file, 'utf8')).toBe(APP_SAVED_B);
  });

  it('bản sao bị yt-dlp ghi dở/hỏng thì không ghi ngược', async () => {
    const s = setup();
    await s.service.saveText(APP_SAVED_A);
    const lease = await s.jar.lease(s.settings);
    writeFileSync(lease.settings!.cookiesFilePath, '');

    await lease.release('success');

    expect(readFileSync(s.file, 'utf8')).toBe(APP_SAVED_A);
  });

  it('tác vụ cũ chưa có dấu vân tay: tệp do yt-dlp ghi (mtime mới hơn) KHÔNG tính là đổi', async () => {
    const s = setup();
    await s.service.saveText(APP_SAVED_A);
    const blockedAt = new Date(Date.now() - 60 * 60_000).toISOString();
    // Dữ liệu thật trước bản sửa: chưa có trạng thái app ghi, tệp mang tiêu đề yt-dlp, mtime mới hơn lúc chặn.
    rmSync(join(s.security, 'cookie-jar-state.json'), { force: true });
    writeFileSync(s.file, YTDLP_ROTATED('cu'));
    const now = new Date();
    utimesSync(s.file, now, now);

    const current = await computeCookieFingerprint(s.settings, s.jar);
    expect(cookiesChangedSinceBlock(undefined, current, blockedAt, 'startup')).toBe(false);
  });
});
