import { createHash, randomUUID } from 'node:crypto';
import { lstat, mkdir, readdir, readFile, realpath, rename, rm, writeFile } from 'node:fs/promises';
import { basename, dirname, isAbsolute, join, resolve } from 'node:path';
import type { CookieArgumentSettings } from '../downloader/ytdlp-cookie-arguments.js';

/**
 * Quản lý tệp cookies Netscape mà yt-dlp dùng (Đợt 1 mục 3, 2026-10-02).
 *
 * Vấn đề: yt-dlp GHI NGƯỢC tệp truyền qua `--cookies` sau mỗi lần chạy (tiêu đề "This file is generated by
 * yt-dlp"). Trước đây tới 6 tiến trình cùng ghi đè MỘT tệp, và app không phân biệt được "người dùng lưu
 * cookies mới" với "yt-dlp tự làm mới cookie xoay vòng".
 *
 * Cách làm:
 * 1. Mỗi lượt chạy yt-dlp nhận một BẢN SAO TẠM riêng (lease) trong security/cookie-runs.
 * 2. Sau lượt KHÔNG lỗi cookies, nếu yt-dlp đã cập nhật bản sao, ghi ngược vào tệp gốc để giữ cookie YouTube
 *    tự xoay vòng — ghi nguyên tử (tệp tạm rồi rename), tuần tự qua khóa, bỏ qua nếu tệp gốc đã đổi trong
 *    lúc chạy (người dùng vừa lưu cookies mới) hoặc bản sao không còn là tệp Netscape hợp lệ.
 * 3. Mỗi lần APP ghi tệp gốc (người dùng lưu, hoặc ghi ngược) đều lưu hash; lưu qua app còn tăng số thế hệ.
 *    Nhờ vậy yt-dlp tự làm mới không bao giờ bị tính là "cookies mới".
 */
/**
 * Kết quả một lượt chạy yt-dlp. Chỉ ghi ngược sau 'success' và 'other-failure' (lỗi KHÔNG liên quan cookies,
 * ví dụ mạng/403). Lỗi cookies, bị hủy, hoặc lỗi chưa phân loại được: không ghi ngược.
 */
export type CookieRunOutcome = 'success' | 'other-failure' | 'cookie-failure' | 'unclassified-failure' | 'aborted';

export interface CookieLease {
  /** Cài đặt cookies để dựng tham số yt-dlp — tệp đã được thay bằng bản sao tạm riêng của lượt này. */
  settings: CookieArgumentSettings | undefined;
  release(outcome: CookieRunOutcome): Promise<void>;
}

export interface CookieJarFileState {
  /** Tăng mỗi khi người dùng lưu cookies qua app. */
  generation: number;
  lastUserSaveSha256: string | null;
  lastUserSaveAt: string | null;
  /** Hash nội dung app ghi vào tệp gốc lần cuối (lưu của người dùng hoặc ghi ngược sau yt-dlp). */
  lastAppWrittenSha256: string | null;
}

interface StateFile {
  version: 1;
  files: Record<string, CookieJarFileState>;
}

const RUNS_FOLDER = 'cookie-runs';
const STATE_FILE = 'cookie-jar-state.json';
/** Tên bản sao tạm do lease() tạo: randomUUID() + .txt. */
const RUN_COPY_NAME = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.txt$/i;

/** Thay đường dẫn tệp cookies gốc trong tham số yt-dlp (--cookies <tệp>) bằng bản sao tạm của lượt này. */
export function withLeasedCookieFile(args: readonly string[], lease: CookieLease): string[] {
  const copy = lease.settings?.cookiesFilePath;
  if (!copy) return [...args];
  return args.map((arg, index) => (index > 0 && args[index - 1] === '--cookies' ? copy : arg));
}

export function sha256(content: Buffer | string): string {
  return createHash('sha256').update(content).digest('hex');
}

/** Tệp Netscape hợp lệ tối thiểu: có ít nhất một dòng cookie 7 cột (bản sao ghi dở/rỗng thì không). */
function looksLikeNetscapeCookies(text: string): boolean {
  return text.split(/\r?\n/).some((line) => !line.startsWith('#') && line.split('\t').length >= 7);
}

function keyOf(path: string): string {
  return resolve(path).toLowerCase();
}

export class CookieJarStore {
  private readonly runsDirectory: string;
  private readonly statePath: string;
  private tail: Promise<unknown> = Promise.resolve();
  /** Lượt mượn mới chờ bước dọn bản sao sót (lúc khởi động) xong, để không bị dọn nhầm. */
  private staleCleanup: Promise<void> = Promise.resolve();

  public constructor(private readonly securityDirectory: string) {
    this.runsDirectory = join(securityDirectory, RUNS_FOLDER);
    this.statePath = join(securityDirectory, STATE_FILE);
  }

  /** Khóa tuần tự trong tiến trình chính: mọi lần ghi tệp gốc/trạng thái đi lần lượt. */
  private exclusive<T>(action: () => Promise<T>): Promise<T> {
    const run = this.tail.then(action, action);
    this.tail = run.catch(() => undefined);
    return run;
  }

  private async readState(): Promise<StateFile> {
    try {
      const parsed = JSON.parse(await readFile(this.statePath, 'utf8')) as Partial<StateFile>;
      if (parsed && parsed.version === 1 && parsed.files && typeof parsed.files === 'object') {
        return { version: 1, files: parsed.files };
      }
    } catch {
      // Chưa có trạng thái (bản cũ) hoặc tệp hỏng: coi như chưa biết gì.
    }
    return { version: 1, files: {} };
  }

  private async writeState(state: StateFile): Promise<void> {
    await mkdir(this.securityDirectory, { recursive: true });
    await this.atomicWrite(this.statePath, JSON.stringify(state, null, 1));
  }

  private async atomicWrite(path: string, content: string | Buffer): Promise<void> {
    const temporary = `${path}.${randomUUID()}.tmp`;
    await writeFile(temporary, content, { mode: 0o600 });
    try {
      await rename(temporary, path);
    } catch (error) {
      await rm(temporary, { force: true });
      throw error;
    }
  }

  public async describe(path: string): Promise<CookieJarFileState | null> {
    const state = await this.readState();
    return state.files[keyOf(path)] ?? null;
  }

  /** Người dùng vừa lưu cookies qua app vào `path`: ghi nhận hash và tăng số thế hệ. */
  public recordUserSave(path: string): Promise<void> {
    return this.exclusive(async () => {
      const hash = sha256(await readFile(path));
      const state = await this.readState();
      const previous = state.files[keyOf(path)];
      state.files[keyOf(path)] = {
        generation: (previous?.generation ?? 0) + 1,
        lastUserSaveSha256: hash,
        lastUserSaveAt: new Date().toISOString(),
        lastAppWrittenSha256: hash
      };
      await this.writeState(state);
    });
  }

  /** Mượn một bản sao tạm riêng cho một lượt chạy yt-dlp. Cookies trình duyệt/không có cookies: không cần sao. */
  public async lease(settings: CookieArgumentSettings | undefined): Promise<CookieLease> {
    const original = settings?.cookiesFilePath.trim();
    if (!settings || !original) return { settings, release: () => Promise.resolve() };
    await this.staleCleanup;
    let content: Buffer;
    try {
      content = await readFile(original);
    } catch {
      // Tệp gốc không đọc được: để yt-dlp tự báo lỗi đúng như trước (không sao chép gì).
      return { settings, release: () => Promise.resolve() };
    }
    await mkdir(this.runsDirectory, { recursive: true });
    const copyPath = join(this.runsDirectory, `${randomUUID()}.txt`);
    await writeFile(copyPath, content, { mode: 0o600 });
    const originalHashAtLease = sha256(content);
    let released = false;
    return {
      settings: { ...settings, cookiesFilePath: copyPath },
      release: async (outcome) => {
        if (released) return;
        released = true;
        try {
          if (outcome === 'success' || outcome === 'other-failure') {
            await this.writeBack(original, copyPath, originalHashAtLease);
          }
        } finally {
          await rm(copyPath, { force: true });
        }
      }
    };
  }

  private writeBack(original: string, copyPath: string, originalHashAtLease: string): Promise<void> {
    return this.exclusive(async () => {
      const updated = await readFile(copyPath).catch(() => null);
      if (!updated) return;
      const updatedHash = sha256(updated);
      if (updatedHash === originalHashAtLease) return;
      if (!looksLikeNetscapeCookies(updated.toString('utf8'))) return;
      const current = await readFile(original).catch(() => null);
      // Tệp gốc đã đổi kể từ lúc mượn (người dùng vừa lưu cookies mới, hoặc lượt khác vừa ghi ngược):
      // không ghi đè bằng bản sao cũ.
      if (!current || sha256(current) !== originalHashAtLease) return;
      await this.atomicWrite(original, updated);
      const state = await this.readState();
      const key = keyOf(original);
      const previous = state.files[key];
      state.files[key] = {
        generation: previous?.generation ?? 0,
        lastUserSaveSha256: previous?.lastUserSaveSha256 ?? null,
        lastUserSaveAt: previous?.lastUserSaveAt ?? null,
        lastAppWrittenSha256: updatedHash
      };
      await this.writeState(state);
    });
  }

  /** Dọn bản sao tạm sót lại khi app bị tắt ngang giữa lượt chạy (chứa cookies — không để nằm lại). */
  /**
   * Chỉ xóa TỆP đúng mẫu tên bản sao (<uuid>.txt) nằm TRỰC TIẾP trong security\cookie-runs. Không làm gì
   * nếu đường dẫn không tuyệt đối, hoặc cookie-runs là liên kết/junction trỏ đi nơi khác (tránh xóa nhầm
   * tệp của người dùng ở thư mục đích). Thư mục con, tệp khác tên, tệp sâu hơn một cấp: giữ nguyên.
   */
  public cleanupStaleRuns(): Promise<void> {
    this.staleCleanup = (async () => {
      if (!this.securityDirectory || !isAbsolute(this.securityDirectory)) return;
      const runs = resolve(this.runsDirectory);
      const info = await lstat(runs).catch(() => null);
      if (!info || !info.isDirectory() || info.isSymbolicLink()) return;
      // So với realpath của thư mục cha (không so với chuỗi gốc): đường dẫn dạng tên ngắn 8.3 (C:\Users\RUNNER~1\…)
      // được realpath mở thành tên dài, so chuỗi gốc thì lệch và không dọn gì (phát hiện trên CI khi phát hành 1.6.0).
      // cookie-runs là liên kết trỏ chỗ khác thì realpath của nó vẫn lệch với <cha thật>\cookie-runs → bỏ qua.
      const real = await realpath(runs).catch(() => null);
      const realParent = await realpath(dirname(runs)).catch(() => null);
      if (!real || !realParent || real.toLowerCase() !== join(realParent, basename(runs)).toLowerCase()) return;
      const entries = await readdir(runs, { withFileTypes: true }).catch(() => []);
      for (const entry of entries) {
        if (!entry.isFile() || !RUN_COPY_NAME.test(entry.name)) continue;
        await rm(join(runs, entry.name), { force: true }).catch(() => undefined);
      }
    })().catch(() => undefined);
    return this.staleCleanup;
  }
}
