import { readFile, stat } from 'node:fs/promises';
import { resolve } from 'node:path';
import type { AppSettings } from '@shared/types/domain.js';
import { sha256, type CookieJarFileState } from './cookie-jar-store.js';

/**
 * "Dấu vân tay" của cấu hình cookies tại một thời điểm — dùng để biết cookies có THẬT SỰ đổi kể từ lúc
 * một video bị chặn hay không (Đợt 1 mục 3, 2026-10-02). Trước đây mỗi lần mở app đều tự chạy lại toàn bộ
 * video bị chặn dù cookies không đổi, tạo vòng lặp "hết hạn → chạy lại → hết hạn".
 *
 * Lưu trong input của tác vụ dưới khóa có chữ "cookie" nên Logger (redactSecrets) tự che toàn bộ khi
 * ghi nhật ký — không bao giờ ghi nội dung cookies hay giá trị hash ra tệp nhật ký.
 */
export type CookieFingerprint =
  | { mode: 'none' }
  | {
      mode: 'file';
      path: string;
      mtimeMs: number;
      size: number;
      sha256: string;
      /** Số lần người dùng đã lưu cookies qua app (CookieJarStore). */
      generation: number;
      lastUserSaveSha256: string | null;
      lastUserSaveAt: string | null;
      lastAppWrittenSha256: string | null;
      /** Tệp hiện mang tiêu đề do yt-dlp ghi (dữ liệu trước bản sửa: yt-dlp ghi thẳng vào tệp gốc). */
      writtenByYtDlp: boolean;
    }
  | { mode: 'file-missing'; path: string }
  | { mode: 'browser'; browser: string; profile: string };

/** Lý do gọi so sánh: lúc mở app, hay ngay sau khi người dùng chủ động lưu cấu hình cookies. */
export type CookieResumeTrigger = 'startup' | 'cookies-saved';

export interface CookieJarStateReader {
  describe(path: string): Promise<CookieJarFileState | null>;
}

export async function computeCookieFingerprint(
  settings: Pick<AppSettings, 'cookiesFilePath' | 'cookiesBrowser' | 'cookiesBrowserProfile'>,
  jar?: CookieJarStateReader | null
): Promise<CookieFingerprint> {
  const filePath = settings.cookiesFilePath.trim();
  if (filePath) {
    const path = resolve(filePath);
    try {
      const [info, content] = await Promise.all([stat(path), readFile(path)]);
      const state = jar ? await jar.describe(path) : null;
      return {
        mode: 'file',
        path,
        mtimeMs: info.mtimeMs,
        size: info.size,
        sha256: sha256(content),
        generation: state?.generation ?? 0,
        lastUserSaveSha256: state?.lastUserSaveSha256 ?? null,
        lastUserSaveAt: state?.lastUserSaveAt ?? null,
        lastAppWrittenSha256: state?.lastAppWrittenSha256 ?? null,
        writtenByYtDlp: /generated by yt-dlp/i.test(content.subarray(0, 512).toString('utf8'))
      };
    } catch {
      return { mode: 'file-missing', path };
    }
  }
  if (settings.cookiesBrowser !== 'none') {
    return { mode: 'browser', browser: settings.cookiesBrowser, profile: settings.cookiesBrowserProfile.trim() };
  }
  return { mode: 'none' };
}

interface StoredFileFingerprint {
  mode: 'file';
  sha256: string;
  generation?: number;
}

function storedMode(value: unknown): string | null {
  if (!value || typeof value !== 'object') return null;
  const mode = (value as { mode?: unknown }).mode;
  return typeof mode === 'string' ? mode : null;
}

function isStoredFile(value: unknown): value is StoredFileFingerprint {
  return storedMode(value) === 'file' && typeof (value as { sha256?: unknown }).sha256 === 'string';
}

/**
 * Cookies hiện tại có phải "cookies mới" so với lúc tác vụ bị chặn không.
 * Tệp cookies — chỉ hai trường hợp được tính là đổi:
 *  (a) người dùng đã LƯU QUA APP (số thế hệ tăng) một nội dung KHÁC nội dung lúc bị chặn;
 *  (b) nội dung tệp khác cả lúc bị chặn lẫn lần app ghi gần nhất → người dùng sửa tệp bên ngoài app.
 *  yt-dlp tự làm mới cookie (được app ghi ngược, nên trùng hash "app ghi lần cuối") KHÔNG bao giờ tính.
 * Tác vụ cũ chưa có dấu vân tay: tính là đổi nếu người dùng đã lưu qua app sau lúc bị chặn, hoặc tệp có
 *  mtime mới hơn lúc bị chặn mà KHÔNG phải do yt-dlp ghi (trước bản sửa yt-dlp ghi thẳng vào tệp gốc).
 * Cookies trình duyệt: không đọc được nội dung để so, nên lúc mở app không bao giờ coi là mới; chỉ khi
 *  người dùng chủ động lưu lại cấu hình (sau khi đăng nhập lại trên trình duyệt) mới chạy lại.
 */
export function cookiesChangedSinceBlock(
  stored: unknown,
  current: CookieFingerprint,
  blockedAt: string | null,
  trigger: CookieResumeTrigger
): boolean {
  if (current.mode === 'none' || current.mode === 'file-missing') return false;
  if (current.mode === 'browser') {
    if (trigger === 'cookies-saved') return true;
    if (storedMode(stored) !== 'browser') return false;
    const previous = stored as { browser?: unknown; profile?: unknown };
    return previous.browser !== current.browser || previous.profile !== current.profile;
  }
  if (isStoredFile(stored)) {
    if (current.sha256 === stored.sha256) return false;
    const savedNewThroughApp =
      current.generation > (stored.generation ?? 0) &&
      current.lastUserSaveSha256 !== null &&
      current.lastUserSaveSha256 !== stored.sha256;
    if (savedNewThroughApp) return true;
    if (current.lastAppWrittenSha256 !== null && current.sha256 === current.lastAppWrittenSha256) return false;
    return true;
  }
  if (stored !== undefined && stored !== null) {
    // Lúc bị chặn chưa dùng tệp (trình duyệt / chưa cấu hình) mà giờ có tệp: người dùng đã đổi cấu hình.
    return storedMode(stored) !== null;
  }
  const blockedAtMs = blockedAt ? Date.parse(blockedAt) : Number.NaN;
  if (!Number.isFinite(blockedAtMs)) return false;
  const userSavedAfterBlock = current.lastUserSaveAt !== null && Date.parse(current.lastUserSaveAt) > blockedAtMs;
  if (userSavedAfterBlock) return true;
  return !current.writtenByYtDlp && current.mtimeMs > blockedAtMs;
}
