import { homedir } from 'node:os';
import { join } from 'node:path';
import type { AppSettings, QualityProfile, ResourceProfile } from '@shared/types/domain.js';
import { DEFAULT_QUALITY_PROFILE_ID, DEFAULT_RESOURCE_PROFILE_ID } from '@shared/constants/app.js';

const base = join(homedir(), 'Videos', 'Download video Tubmedia');
export const defaultAppSettings: AppSettings = {
  theme: 'system', language: 'vi', minimizeToTray: false, startWithWindows: false, closeBehavior: 'ask',
  defaultSourceFolder: join(base, 'Bộ nhớ nguồn'), defaultTempFolder: join(base, 'Tệp tạm'), defaultOutputFolder: join(base, 'Thành phẩm'),
  defaultQualityProfileId: DEFAULT_QUALITY_PROFILE_ID, defaultResourceProfileId: DEFAULT_RESOURCE_PROFILE_ID,
  verificationLevel: 'standard', sourceCachePolicy: 'manual', sourceCacheDays: 30, logRetentionDays: 30,
  appUpdateChannel: 'stable', toolUpdateChannel: 'stable', autoCheckAppUpdates: false, autoCheckToolUpdates: false,
  toolManifestUrl: '', appFeedUrl: '', ytdlpPath: '', ffmpegPath: '', ffprobePath: '', aria2cPath: '', cookiesFilePath: '',
  cookiesBrowser: 'none', cookiesBrowserProfile: '', proxy: '', rateLimit: '', useAria2c: true, aria2Connections: 16, maxGlobalDownloadWorkers: 2, downloadConcurrentFragments: 2,
  downloadLaneCount: 2, mergeLaneCount: 2, maxGlobalMergeJobs: 2, downloadCompatibilityMode: 'source', downloadMinHeight: 0, downloadMaxHeight: 0, downloadMinFps: 0, downloadMaxFps: 0,
  downloadCodecPreference: 'auto', downloadContainerPreference: 'auto', downloadMinVideoBitrateKbps: 0, downloadVideoBitrateKbps: 0,
  downloadMinAudioBitrateKbps: 0, downloadAudioBitrateKbps: 0,
  downloadAllowBelowMinimum: false, downloadVerifyEntireFile: false, progressRefreshMs: 300
};

export const builtInResourceProfiles: ResourceProfile[] = [
  { id: 'resource-low', name: 'Máy yếu', description: 'Ưu tiên phản hồi hệ thống.', downloadWorkers: 1, analyzeWorkers: 1, normalizeWorkers: 1, remuxWorkers: 1, clipWorkers: 1, ffmpegThreads: 3, filterThreads: 1, filterComplexThreads: 1, processPriority: 'below_normal', cpuSoftLimitPercent: 85, memoryFreeMinimumBytes: 4 * 1024 ** 3, diskFreeMinimumBytes: 15 * 1024 ** 3, gpuJobs: 0, builtIn: true },
  { id: 'resource-balanced', name: 'Cân bằng', description: 'Phù hợp phần lớn máy phổ thông; cho phép tối đa 2 bước chuẩn hóa nhẹ song song và tự dùng GPU khi FFmpeg xác minh được.', downloadWorkers: 2, analyzeWorkers: 2, normalizeWorkers: 2, remuxWorkers: 2, clipWorkers: 1, ffmpegThreads: 5, filterThreads: 2, filterComplexThreads: 2, processPriority: 'below_normal', cpuSoftLimitPercent: 88, memoryFreeMinimumBytes: 6 * 1024 ** 3, diskFreeMinimumBytes: 20 * 1024 ** 3, gpuJobs: 1, builtIn: true },
  { id: 'resource-interactive', name: 'Máy trạm cân bằng', description: 'Tối ưu máy nhiều nhân: chuẩn hóa/remux song song có giới hạn, ưu tiên GPU đã kiểm tra và vẫn giữ Windows phản hồi.', downloadWorkers: 2, analyzeWorkers: 3, normalizeWorkers: 2, remuxWorkers: 2, clipWorkers: 1, ffmpegThreads: 6, filterThreads: 3, filterComplexThreads: 3, processPriority: 'below_normal', cpuSoftLimitPercent: 88, memoryFreeMinimumBytes: 8 * 1024 ** 3, diskFreeMinimumBytes: 25 * 1024 ** 3, gpuJobs: 1, builtIn: true },
  { id: 'resource-full', name: 'Toàn bộ hiệu năng', description: 'Dành cho máy mạnh: tối đa 3 bước chuẩn hóa và 4 remux đồng thời; tự dùng tối đa 2 phiên GPU khi khả dụng.', downloadWorkers: 4, analyzeWorkers: 4, normalizeWorkers: 3, remuxWorkers: 4, clipWorkers: 2, ffmpegThreads: 6, filterThreads: 3, filterComplexThreads: 3, processPriority: 'normal', cpuSoftLimitPercent: 98, memoryFreeMinimumBytes: 4 * 1024 ** 3, diskFreeMinimumBytes: 15 * 1024 ** 3, gpuJobs: 2, builtIn: true }
];

export const builtInQualityProfiles: QualityProfile[] = [
  { id: 'quality-720p-fast', name: '720p nhanh và nhẹ', description: 'Xuất tối đa 1280x720, H.264/AAC; phù hợp máy yếu hoặc xem nhanh.', mode: 'custom', maxWidth: 1280, maxHeight: 720, allowUpscale: false, fpsMode: '30', customFps: null, videoCodec: 'h264', encoder: 'cpu_auto', crf: 20, cq: 22, preset: 'fast', pixelFormat: 'yuv420p', hdrMode: 'tonemap_sdr', audioMode: 'aac_256', sampleRate: 48000, forceStereo: true, builtIn: true },
  { id: 'quality-reference-1080p', name: '1080p đồng nhất · CapCut/thiết bị rộng', description: 'Mạnh nhất khi cần mọi video về 1920x1080/30 FPS H.264/AAC để dựng và phát ổn định; dùng libx264 CRF 18 veryfast.', mode: 'custom', maxWidth: 1920, maxHeight: 1080, allowUpscale: true, fpsMode: '30', customFps: null, videoCodec: 'h264', encoder: 'libx264', crf: 18, cq: 20, preset: 'veryfast', pixelFormat: 'yuv420p', hdrMode: 'tonemap_sdr', audioMode: 'aac_256', sampleRate: 48000, forceStereo: true, builtIn: true },
  { id: 'quality-1440p', name: '1440p cân bằng chi tiết', description: 'Mạnh nhất cho màn hình 2K: giữ nhiều chi tiết hơn 1080p nhưng nhẹ và nhanh hơn 4K.', mode: 'custom', maxWidth: 2560, maxHeight: 1440, allowUpscale: false, fpsMode: 'source', customFps: null, videoCodec: 'h264', encoder: 'cpu_auto', crf: 17, cq: 19, preset: 'medium', pixelFormat: 'yuv420p', hdrMode: 'auto', audioMode: 'aac_320', sampleRate: 48000, forceStereo: false, builtIn: true },
  { id: 'quality-4k', name: '4K/HEVC tối đa chi tiết', description: 'Mạnh nhất cho nguồn 4K và lưu trữ dài hạn; HEVC giữ chi tiết cao mà không phóng to giả nguồn thấp.', mode: 'custom', maxWidth: 3840, maxHeight: 2160, allowUpscale: false, fpsMode: 'source', customFps: null, videoCodec: 'hevc', encoder: 'cpu_auto', crf: 17, cq: 19, preset: 'medium', pixelFormat: 'yuv420p', hdrMode: 'auto', audioMode: 'aac_320', sampleRate: 48000, forceStereo: false, builtIn: true },
  { id: 'quality-highest', name: 'Theo nguồn · bảo toàn tối đa', description: 'Mạnh nhất khi ưu tiên chất lượng, FPS, HDR, độ sâu màu và bitrate gần nguồn hơn tốc độ xử lý.', mode: 'highest_source', maxWidth: null, maxHeight: null, allowUpscale: false, fpsMode: 'source', customFps: null, videoCodec: 'copy', encoder: 'libx264', crf: 14, cq: 16, bitrateMode: 'source_average', preset: 'slow', pixelFormat: 'yuv420p', hdrMode: 'keep', audioMode: 'copy_if_compatible', sampleRate: 48000, forceStereo: false, builtIn: true },
  { id: 'quality-smart-merge', name: 'Ghép thông minh · ít mã hóa lại', description: 'Chỉ xử lý tệp thật sự lệch chuẩn, dùng cache, remux nhanh và tự chọn GPU đã xác minh; giữ bitrate gần nguồn.', mode: 'smart_merge', maxWidth: null, maxHeight: null, allowUpscale: false, fpsMode: 'source', customFps: null, videoCodec: 'copy', encoder: 'auto', crf: 16, cq: 19, bitrateMode: 'source_average', preset: 'veryfast', pixelFormat: 'yuv420p', hdrMode: 'auto', audioMode: 'copy_if_compatible', sampleRate: 48000, forceStereo: false, builtIn: true },
  { id: 'quality-source-size', name: 'Nguồn nguyên bản · ghép nhanh thông minh', description: 'KHUYÊN DÙNG. Stream-copy khi tương thích, remux khi chỉ lỗi container/timestamp, chỉ mã hóa clip lệch chuẩn và dùng lại cache; tự dùng GPU đã xác minh.', mode: 'smart_merge', maxWidth: null, maxHeight: null, allowUpscale: false, fpsMode: 'source', customFps: null, videoCodec: 'copy', encoder: 'auto', crf: 16, cq: 19, bitrateMode: 'source_average', preset: 'veryfast', pixelFormat: 'yuv420p', hdrMode: 'auto', audioMode: 'copy_if_compatible', sampleRate: 48000, forceStereo: false, builtIn: true },
  { id: 'quality-1080p', name: '1080p tương thích phổ thông', description: 'Mạnh nhất cho TV, điện thoại và trình dựng phổ biến: H.264/AAC 48 kHz, không phóng lớn giả.', mode: 'compatible_1080p', maxWidth: 1920, maxHeight: 1080, allowUpscale: false, fpsMode: 'source', customFps: null, videoCodec: 'h264', encoder: 'cpu_auto', crf: 18, cq: 20, preset: 'medium', pixelFormat: 'yuv420p', hdrMode: 'auto', audioMode: 'aac_256', sampleRate: 48000, forceStereo: false, builtIn: true },
  { id: 'quality-smooth', name: 'Mã hóa nền · máy vẫn mượt', description: 'Mạnh nhất khi vẫn cần làm việc trên Windows trong lúc xuất; CPU chạy ưu tiên thấp và preset nhanh.', mode: 'smooth_background', maxWidth: 1920, maxHeight: 1080, allowUpscale: false, fpsMode: 'source', customFps: null, videoCodec: 'h264', encoder: 'cpu_auto', crf: 19, cq: 21, preset: 'fast', pixelFormat: 'yuv420p', hdrMode: 'auto', audioMode: 'aac_256', sampleRate: 48000, forceStereo: false, builtIn: true },
  { id: 'quality-max-cpu', name: 'CPU tối đa · chất lượng cao', description: 'Mạnh nhất khi không có GPU tương thích và chấp nhận xử lý lâu hơn để đạt chất lượng libx264 CRF thấp.', mode: 'maximum_cpu', maxWidth: null, maxHeight: null, allowUpscale: false, fpsMode: 'source', customFps: null, videoCodec: 'h264', encoder: 'libx264', crf: 16, cq: 18, preset: 'slow', pixelFormat: 'yuv420p', hdrMode: 'auto', audioMode: 'aac_320', sampleRate: 48000, forceStereo: false, builtIn: true }
];
