!define PRODUCT_NAME "Download video Tubmedia"
!define PRODUCT_VERSION "1.2.3"
!define PRODUCT_FILE_VERSION "1.2.3.0"
!define PRODUCT_DESCRIPTION "Tubmedia Ã¢â‚¬â€ Ã¡Â»Â©ng dÃ¡Â»Â¥ng tÃ¡ÂºÂ£i video Ã„â€˜a nÃ¡Â»Ân tÃ¡ÂºÂ£ng vÃƒÂ  ghÃƒÂ©p video chuyÃƒÂªn nghiÃ¡Â»â€¡p, tÃ¡Â»â€˜i Ã†Â°u giao diÃ¡Â»â€¡n, cÃ¡ÂºÂ­p nhÃ¡ÂºÂ­t an toÃƒÂ n vÃƒÂ  kiÃ¡ÂºÂ¿n trÃƒÂºc phÃƒÂ¡t hÃƒÂ nh dÃƒÂ i hÃ¡ÂºÂ¡n."
!define COMPANY_NAME "ÄÃ¬nh Duy Tubmedia"
!define APP_ID "com.tubmedia.download-video"
!define APP_EXE "Download video Tubmedia.exe"
!define INSTALL_REGISTRY_KEY "Software\Tubmedia\DownloadVideo"
!define DEFAULT_INSTALL_DIRECTORY_NAME "Download video Tubmedia"
!define LEGACY_APP_ID "com.video.download.merge.studio.pro"
!define LEGACY_PRODUCT_NAME "Video Download Merge Studio Pro"
!define APP_SOURCE "C:\Users\Hi\TubmediaDev\Tubmedia_Next_Fixed_20260728-090256\Tubmedia_Next\release\win-unpacked"
!define APP_ICON "C:\Users\Hi\TubmediaDev\Tubmedia_Next_Fixed_20260728-090256\Tubmedia_Next\resources\icon.ico"
!define OUTPUT_FILE "C:\Users\Hi\TubmediaDev\Tubmedia_Next_Fixed_20260728-090256\Tubmedia_Next\release\Download video Tubmedia-Setup-1.2.3-x64.exe"
